# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Adam Raffe
tagline:             'Cloud, Data Centre & Networking'
description:         'Adam's blog, focused on cloud computing, data centre & networking'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Adam Raffe
  url:               https://twitter.com/adamraffe
  email:             

# Custom vars
